// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzjfnebtbsdrkeuixebq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6amZuZWJ0YnNkcmtldWl4ZWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDcyODksImV4cCI6MjA3MDA4MzI4OX0.z_BTLr4y_Re-wQ6ONSzkr_f2iGIwWNsnxfRHsNVEXqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});